var search={
  "Activity Instances Collection": "http://fuzzy-sl.squirrel.link/data/Activity_collection",
  "Agent Instances Collection": "http://fuzzy-sl.squirrel.link/data/Agent_collection",
  "Bruttium": "http://fuzzy-sl.squirrel.link/data/crotonsite_2001",
  "Calabria (Italy)": "http://fuzzy-sl.squirrel.link/data/crotonsite_2008",
  "Calabria (Regione)": "http://fuzzy-sl.squirrel.link/data/crotonsite_2002",
  "Calabria (anc. Bruttium)": "http://fuzzy-sl.squirrel.link/data/crotonsite_1004",
  "Crotone, loc. Via Paternostro 1974": "http://fuzzy-sl.squirrel.link/data/crotonsite_3002",
  "Curinga (Italy)": "http://fuzzy-sl.squirrel.link/data/crotonsite_2011",
  "Curinga 1916 (IGCH 1881 / Noe 285)": "http://fuzzy-sl.squirrel.link/data/crotonsite_3004",
  "Curinga, 30 km. WSW of Catanzaro, Bruttium": "http://fuzzy-sl.squirrel.link/data/crotonsite_1007",
  "Entity Instances Collection": "http://fuzzy-sl.squirrel.link/data/Entity_collection",
  "ExternalRepository Instances Collection": "http://fuzzy-sl.squirrel.link/data/ExternalRepository_collection",
  "Fiume Esaro 1967 (gennaio)": "http://fuzzy-sl.squirrel.link/data/crotonsite_3003",
  "Georeferencing Instances Collection": "http://fuzzy-sl.squirrel.link/data/Georeferencing_collection",
  "Ionian Shore, Bruttium": "http://fuzzy-sl.squirrel.link/data/crotonsite_1006",
  "Leucopetra (cape)": "http://fuzzy-sl.squirrel.link/data/crotonsite_2003",
  "Paestum (Italy)": "http://fuzzy-sl.squirrel.link/data/crotonsite_2006",
  "Paestum (anc. Poseidonia), Lucania": "http://fuzzy-sl.squirrel.link/data/crotonsite_1002",
  "Person Instances Collection": "http://fuzzy-sl.squirrel.link/data/Person_collection",
  "Place Instances Collection": "http://fuzzy-sl.squirrel.link/data/Place_collection",
  "Point Instances Collection": "http://fuzzy-sl.squirrel.link/data/Point_collection",
  "Province of Brindisi (Italy)": "http://fuzzy-sl.squirrel.link/data/crotonsite_2010",
  "San Giorgio Ionico 1949": "http://fuzzy-sl.squirrel.link/data/crotonsite_3001",
  "Shepherd - Bruttium (Calabria) - 1911": "http://fuzzy-sl.squirrel.link/data/crotonsite_2004",
  "Site Instances Collection": "http://fuzzy-sl.squirrel.link/data/Site_collection",
  "South Italy": "http://fuzzy-sl.squirrel.link/data/crotonsite_2009",
  "Strongoli (Italy)": "http://fuzzy-sl.squirrel.link/data/crotonsite_2007",
  "Strongoli (anc. Petelia), 25 km. N of Croton, Bruttium": "http://fuzzy-sl.squirrel.link/data/crotonsite_1003",
  "Taranto (Italy)": "http://fuzzy-sl.squirrel.link/data/crotonsite_2005",
  "Taranto, Via Oberdan": "http://fuzzy-sl.squirrel.link/data/crotonsite_1001"
}